# Generated by Django 3.2.5 on 2021-10-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_scrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='scrap',
        ),
    ]
