# Generated by Django 3.2.5 on 2021-10-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211019_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='scrap',
        ),
    ]
